[project]
name = "fine-tune"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gh>=0.0.4",
    "huggingface-hub>=0.29.1",
    "torch>=2.6.0",
    "transformers>=4.49.0",
]
